version: "3.8"

services:
  postgresdb:
    env_file:
      - ./.env
    image: postgres:latest
    volumes:
      - db-data:/home/ingadi/db/data
    networks:
      - ingadi-network
    container_name: "ingadidb"
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
  ingadi-server:
    build: .
    env_file:
      - ./.env
    volumes:
      - server-data:/home/ingadi/server
      - node_modules:/home/ingadi/server/node_modules
    environment:
      - POSTGRES_URL=postgresdb
    networks:
      - ingadi-network
    container_name: "ingadi-server"
    command: yarn prod
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    deploy:
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure
 
networks:
    ingadi-network:
volumes:
    db-data:
    server-data:
    node_modules: